# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^CHANGELOG\.md$

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        additional_dependencies:
          - emotional==0.5.1

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies: [tomli==2.2.1]
      args: ["--write-changes"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.16.0
    hooks:
    - id: markdownlint-cli2
      args: ["--fix"]
      exclude: ^tests/data

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        exclude: .+\.(py|md)$  # Already linted

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        files: ^pelican/plugins/frontmark
        additional_dependencies:
          - types-PyYAML==6.0.12.20241221
          - types-Pygments==2.18.0.20240506
          - types-commonmark==0.9.2.20240106
